version: "2.4"
services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    restart: unless-stopped
    devices:
      - /dev/net/tun
    cap_add:
      - net_admin # required to modify network interfaces
    ports:
      - 8112:8112
      - 6789:6789
    init: true
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      SERVER_COUNTRIES: Singapore
      WIREGUARD_PRIVATE_KEY: "${WG_PRIVATE}"
      PORT_FORWARD_ONLY: on
      VPN_PORT_FORWARDING: on
      WIREGUARD_ADDRESSES: 10.2.0.2/32
      VPN_PORT_FORWARDING_UP_COMMAND: "/bin/sh -c 'wget -O- --retry-connrefused --post-data 'json={\"listen_port\":{{PORTS}}}' http://127.0.0.1:8112/api/v2/app/setPreferences 2>&1'"
    volumes:
      - ${CONF_ROOT}/Config/vpn:/vpn # OpenVPN configuration
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.rule: Host(`torrent.local.viryadh.dev`)
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.service: qbittorrent
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8112
      traefik.http.routers.qbittorrent.tls.certresolver: le
      traefik.http.routers.qbittorrent.tls.domains[0].main: "*.local.viryadh.dev"
      traefik.http.routers.nzbget.rule: Host(`nzbget.local.viryadh.dev`)
      traefik.http.routers.nzbget.entrypoints: websecure
      traefik.http.routers.nzbget.service: nzbget
      traefik.http.services.nzbget.loadbalancer.server.port: 6789
      traefik.http.routers.nzbget.tls.certresolver: le
      traefik.http.routers.nzbget.tls.domains[0].main: "*.local.viryadh.dev"
    healthcheck:
      test: /gluetun-entrypoint healthcheck
      interval: 20s
      retries: 3
      start_period: 10s
      timeout: 10s
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_healthy
        restart: true
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ}
      - WEBUI_PORT=8112
    volumes:
      - ${ROOT}/Data/Downloads:/data/Downloads # downloads folder
      - ${CONF_ROOT}/Config/qbittorrent:/config # config files
  nzbget:
    container_name: nzbget
    image: lscr.io/linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_healthy
        restart: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    volumes:
      - ${CONF_ROOT}/Config/nzbget:/config
      - ${ROOT}/Data/Downloads/Usenet:/data/Downloads
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_ROOT}/Config/jackett:/config # config files
    labels:
      traefik.enable: true
      traefik.http.routers.jackett.rule: Host(`jackett.local.viryadh.dev`)
      traefik.http.routers.jackett.entrypoints: websecure
      traefik.http.routers.jackett.tls.certresolver: le
      traefik.http.routers.jackett.tls.domains[0].main: "*.local.viryadh.dev"
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    links:
      - vpn:vpn
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=dark
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_ROOT}/Config/sonarr:/config # config files
      - ${ROOT}/Data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.local.viryadh.dev`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls.certresolver: le
      traefik.http.routers.sonarr.tls.domains[0].main: "*.local.viryadh.dev"
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    links:
      - vpn:vpn
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=dark
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_ROOT}/Config/radarr:/config # config files
      - ${ROOT}/Data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr.local.viryadh.dev`)
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.tls.certresolver: le
      traefik.http.routers.radarr.tls.domains[0].main: "*.local.viryadh.dev"
  overseerr: 
    image: ghcr.io/seerr-team/seerr:v3.1.0
    init: true
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- BASE_URL=/ombi #optional 
    labels:
      traefik.enable: true
      traefik.http.routers.ombi.rule: Host(`jellyseer.local.viryadh.dev`)
      traefik.http.routers.ombi.entrypoints: websecure
      traefik.http.services.ombi.loadbalancer.server.port: 5055
      traefik.http.routers.ombi.tls.certresolver: le
      traefik.http.routers.ombi.tls.domains[0].main: "*.local.viryadh.dev"
    volumes: 
      - ${CONF_ROOT}/Config/overseerr:/app/config 
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_ROOT}/Config/bazarr:/config
      - ${ROOT}/Data/Videos:/data/media #optional
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: Host(`bazarr.local.viryadh.dev`)
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.tls.certresolver: le
      traefik.http.routers.bazarr.tls.domains[0].main: "*.local.viryadh.dev"
  jellyfin-server:
    container_name: jellyfin-server
    image: linuxserver/jellyfin:10.11.7
    restart: unless-stopped
    network_mode: host
    group_add:
      - "44"  # add video group
      - "104" # add render group
      - "106"
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`media.local.viryadh.dev`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.service: jellyfin-server
      traefik.http.services.jellyfin-server.loadbalancer.server.port: 8096
      traefik.http.routers.jellyfin.tls.certresolver: le
      traefik.http.routers.jellyfin.tls.domains[0].main: "*.local.viryadh.dev"
      traefik.http.routers.jellyfin-local.rule: Host(`media.toshibalinux.local`)
      traefik.http.routers.jellyfin-local.entrypoints: web
      traefik.http.routers.jellyfin-local.service: jellyfin-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} # timezone, defined in .env
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
      #- JELLYFIN_DATA_DIR=/config/data #Uncomment for Jellyfin Images
      #- JELLYFIN_CONFIG_DIR=/config #Uncomment for Jellyfin Images
      #- JELLYFIN_LOG_DIR=/config/log #Uncomment for Jellyfin Images
      #- JELLYFIN_CACHE_DIR=/config/cache #Uncomment for Jellyfin Images
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
    volumes:
      - ${CONF_ROOT}/Config/jellyfin-lsio/Config:/config
      - ${CONF_ROOT}/Config/jellyfin-lsio/Cache:/cache
      - ${ROOT}/Data/Videos:/data/Videos
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:2.7.3
    container_name: resilio-sync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_ROOT}/Config/resilio:/config
      - ${ROOT}/Sync:/downloads
      - ${ROOT}/Data/Downloads:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.resilio.rule: Host(`sync.local.viryadh.dev`)
      traefik.http.routers.resilio.entrypoints: websecure
      traefik.http.routers.resilio.service: resilio-web
      traefik.http.routers.resilio.tls.certresolver: le
      traefik.http.routers.resilio.tls.domains[0].main: "*.local.viryadh.dev"
      traefik.http.services.resilio-web.loadbalancer.server.port: 8888
      traefik.tcp.routers.resilio-sync.rule: HostSNI(`*`)
      traefik.tcp.routers.resilio-sync.entrypoints: sync
      traefik.tcp.routers.resilio-sync.service: resilio-sync
      traefik.tcp.services.resilio-sync.loadbalancer.server.port: 55555
      traefik.udp.routers.resilio-sync.entrypoints: sync-udp
      traefik.udp.routers.resilio-sync.service: resilio-sync
      traefik.udp.services.resilio-sync.loadbalancer.server.port: 55555
